---
ansible_host: "ct01004.{{ inv_all_root_root_domain }}"
fqdn: "ct01004.{{ inv_all_root_root_domain }}"
ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
ansible_become_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
in_disable_set_hostname: true
